---
title:     "Memoria científico-técnica"
subtitle:  |
  CaMMTRIP: Caracterización de Modelos Multidimensionales en la Teoría de Respuesta
  al Ítem a través de sus Parámetros
date-meta: 2025-02-21
date:      2025-02-21
format:
  pdf:     default
  docx:    default
bibliography: ../www/references.bib
---

# Datos identificativos

## Proyecto

**Título:** Caracterización de Modelos Multidimensionales en la Teoría de Respuesta al Ítem a través de sus Parámetros

**Acrónimo:** CaMMTRIP

## Investigador Principal

**Nombre:** Daniel Vicente Morillo Cuadrado

**Cargo**: Profesor Ayudante Doctor

## Miembros del equipo de investigación

**Nombre:** Mario Luzardo Verde

**Afiliación:** Universidad de la República (Uruguay)

**Cargo:** Profesor Titular

{{< pagebreak >}}

# Resumen

<!-- máximo 1000 palabras -->

{{< pagebreak >}}

# Antecedentes

<!-- máximo una página -->

La Teoría de Respuesta al Ítem (*Item Response Theory*, IRT) es uno de los desarrollos teóricos más importantes del pasado siglo en el ámbito de la psicometría y medición educativa.
En su versión paramétrica, ampliamente extendida, la IRT se propone modelar las propiedades de los estímulos (ítems) en base a una serie de parámetros que, junto con los rasgos latentes de las personas, caracterizan las probabilidades de respuesta a cada categoría.
La IRT multidimensional (MIRT) extiende estos modelos a la medición de constructos multivariados.
Dada su convergencia con los modelos factoriales [@mcdonald1999], la MIRT es, a día de hoy, una de las bases fundamentales de la teoría de la medición [@contempo2005].

El modelo logístico de dos parámetros [*2-Parameter Logistic,* 2PL; @lord1968] es uno de los modelos paramétricos de IRT más ampliamente utilizados y estudiados; de acuerdo al mismo, cada ítem se caracteriza por un parámetro de dificultad, que determina la probabilidad de acertar el ítem, y uno de discriminación, interpretado como su *validez* o capacidad para diferenciar entre personas con nivel de rasgo alto y bajo.
Su versión multidimensional (*Multidimensional 2-Parameter Logistic*, M2PL) asume que el ítem tiene un vector de discriminación en lugar de un único valor, además de un parámetro de *intersección*.
En contraste con el modelo 2PL, estos parámetros no son directamente interpretables.
Por este motivo, @reckase1985 propuso una definición formal de la dificultad para ítems multidimensionales y, aplicándola al modelo M2PL, obtuvo su expresión.
En la misma línea, @reckase1991 propusieron una definición de la discriminación multidimensional y derivaron su expresión para el modelo M2PL.
No obstante, estas definiciones asumen la ortogonalidad del espacio latente.
Esto en la práctica se traduce en su limitación a la medida de rasgos latentes no correlacionados.
Para poder generalizarlas al dominio de ítems no cognitivos (i.e., cuestionarios autoinformados), es necesario relajar este supuesto.

Aplicando las definiciones de @reckase1985 y @reckase1991, @morillo extienden las expresiones de la dificultad y discriminación multidimensional del modelo M2PL a ejes no ortogonales [@zhang1999].
Además, mostraron cómo la representación bidimensional de los ítems [@ackerman1996] podía realizarse en ejes no ortogonales.
A pesar de ello, existen varias cuestiones por resolver para poder aplicar estas definiciones a otros modelos de IRT multidimensional (MIRT): En primer lugar, no está claro cómo se definen estos parámetros en modelos distintos del M2PL, aunque muchas instancias en la literatura los aplican de forma acrítica [e.g., @huang2020; @steinley2019; @kim2018].
Además, su representación bidimensional, si bien aporta información muy útil para el diseño y construcción de tests, limita sus aplicaciones a instrumentos que miden únicamente dos rasgos.

{{< pagebreak >}}

# Justificación

El modelo M2PL resulta prácticamente equivalente al modelo factorial para ítems dicotómicos [@mcdonald1999].
No obstante, en la investigación aplicada no suelen utilizarse ítems de respuesta dicotómica, por lo que los resultados antes mencionados, si bien constituyen un punto de partida, no son ampliamente aplicables.
Los modelos de análisis factorial de ítems contemplan la posibilidad de respuestas en escalas graduadas "tipo Likert", lo cual también es abordable desde el punto de vista de la TRI [@samejima1968].
Ahora bien, bajo este supuesto no sería necesario estudiar la MIRT más que como un caso paraticular del modelo factorial.
Sin embargo, los modelos MIRT permiten una mayor flexibilidad en el modelado de los fenómenos de respuesta.
Sin ánimo de ser exhaustivos, algunos ejemplos en el dominio de los instrumentos cognitivos son:

-   Modelado del "pseudoazar": Ante la posibilidad de acertar un ítem de manera aleatoria, el Modelo Multidimensional Logístico de 3 Parámetros (M3PL) permite estimar un parámetro interpretable como "acierto por azar".

-   Modelado del "lapsus": Como en el caso anterior, el Modelo Multidimensional Logístico de 4 Parámetros (M4PL) permite estimar un parámetro interpretable como "fallo por lapsus o desliz".

-   Crédito Parcial: En el caso de ítems de opción múltiple, el Modelo Multidimensional de Crédito Parcial (MPCM) permite estimar el conocimiento parcial a partir del análisis diferencial de los distractores.

Asimismo en el ámbito no cognitivo se pueden considerar, entre otros:

-   Versiones multidimensionales de modelos para ítems con supuestos de medida no monótonos o "de punto ideal", como el Modelo de Coseno Hiperbólico [HCM, @andrich1993], o el Generalized Graded Unfolding Model [GGUM, @roberts2000].

-   Modelos para ítems de elección forzosa multidimensionales, como son el caso de TRI Thurstoniana o TIRT [@maydeu-olivares2010], el Multi-Unidimensional Pairwise Preference Model [MUPP, @stark2005] o su versión para ítems monótonos, el MUPP-2PL [@morillo2016].

Todos estos modelos van mucho más allá de la equivalencia con el modelo factorial, permitiendo el estudio pormenorizado del proceso de respuesta y una mayor precisión en el estudio de los rasgos y fenómenos objeto de la medición.
Por lo tanto, en base a las derivaciones teóricas anteriormente mencionadas, resulta necesario generalizar las definiciones de los parámetros multidimensionales dadas por @reckase1985 y @reckase1991 a otros modelos MIRT.
Yendo incluso más allá, conviene justificar teóricamente la definción dada por @zhang1999 para modelos MIRT semiparamétricos.

<!-- máximo una página -->

{{< pagebreak >}}

# Objetivos

CaMMTRIP tiene por objetivo principal **generalizar la caracterización de modelos MIRT en coordenadas oblicuas mediante parámetros multidimensionales** (O1) más allá del modelo M2PL.
Asimismo, y en base al objetivo anterior, se persigue **hallar la representación vectorial en coordenadas oblicuas de los ítems según los modelos MIRT anteriormente estudiados** (O2).
Por último, se pretende **demostrar la aplicación práctica de la caracterízación multidimensional y representación de los modelos** (O3), utilizando tanto estudios de simulación, como ejemplos de instrumentos reales en la literatura estimados con modelos MIRT.

Para ello, se proponen los siguientes objetivos específicos:

-   O1.1: **Derivar las expresiones generalizadas de los parámetros multidimensionales para modelos paramétricos** distintos al M2PL.
    Entre otros, se busca estudiar estos parámetros en las versiones multidimensionales del Modelo Logístico de 3 Parámetros, el Modelo de Crédito Parcial, el Modelo de Respuesta Graduada, así como del Modelo Multidimensional No Compensatorio.

-   O1.2: En base al objetivo O1.1, aplicando un método inductivo, **investigar la posible formulación generalizada de los parámetros multidimensionales para modelos semiparamétricos y no paramétricos**.

-   O2.1: **Proponer las formas de representación vectorial bidimensional en coordenadas oblicuas adecuadas a los modelos investigados** en el objetivo O1.1.

-   O2.2: **Investigar métodos de visualización de las representaciones vectoriales en tres dimensiones**.

-   O3.1: **Ejemplificar la aplicación y uso de los parámetros multidimensionales y su representación gráfica vectorial mediante datos simulados**.

-   O3.2: **Demostrar la aplicación práctica de los resultados, aplicando las definiciones propuestas a ejemplos de modelos MIRT aplicados en medición psicológica y educativa**.

<!-- máximo una página -->

{{< pagebreak >}}

# Metodología

Los objetivos perseguidos en este trabajo responden principalmente al estudio de la formulación teórica de los modelos MIRT estudiados.
Por lo tanto, el método empleado en este proyecto será principalmente deductivo, utilizando los postulados formales del cálculo, el álgebra matricial, y la geometría euclidea.
Asimismo, se utilizarán métodos de simulación computacional para investigar la aplicación de estos resultados a los modelos.
Por último, se realizarán búsquedas bibliográficas y utilizarán procedimientos de estimación de MIRT, para aplicar estos resultados a ejemplos reales de medición psicológica y educativa.

1.  Partiendo de la formulación de cada modelo (O1.1), se aplicará el método de cálculo del punto de máxima pendiente [@reckase1985, @reckase1991] para obtener los parámetros de dificultad y discriminación de los ítems según cada uno de los modelos bajo estudio.
    Para ello, será necesario aplicar métodos de cálculo diferencial y álgebra matricial, tal y como se ha hecho anteriormente en el estudio del M2PL [@morillo].

2.  Se investigará asimismo la aplicación de estos métodos al dominio de los modelos semiparamétricos y no paramétricos (O1.2), partiendo de la abstracción de los resultados anteriores y la generalización de los métodos aplicados en el objetivo O1.1.

3.  Aplicando la geometría euclidea, se obtendrán las representaciones gráficas vectoriales de los ítems, de acuerdo a los diferentes modelos, en coordenadas oblicuas, ya sea en dos (O2.1) o en tres (O2.2) dimensiones.

4.  Se realizarán estudios de simulación para la generación de ítems y respuestas en función de cada uno de los modelos multidimensionales bajo estudio (O3.1).
    Aplicando diferentes métodos de estimación implementados en el paquete {mirt} para R @chalmers2012, se estimarán los parámetros de los ítems de acuerdo al modelo utilizado.

5.  Para ejemplificar la aplicación y utilidad práctica de las definiciones propuestas de los parámetros (O3.2), se realizará una búsqueda bibliográfica sistemática en la literatura sobre medición psicológica y educativa.
    Tras seleccionar los artículos que apliquen los modelos MIRT estudiados, se realizará el cálculo de los parámetros multidimensionales y la representación vectorial de los ítems.

<!-- máximo una página -->

{{< pagebreak >}}

# Plan de trabajo

<!-- máximo una página -->

{{< pagebreak >}}

# Impacto y plan de difusión

-   IMPS 2025

-   Psychometrika <!-- Acuerdo transformativo Cambridge University Press -->

<!-- máximo una página -->

{{< pagebreak >}}

# Presupuesto

```{=html}
<!--
lo más detallado posible, de los gastos del proyecto para el que se solicita la ayuda.
Quedan excluidas comidas o pausas-café.
Toda solicitud con un presupuesto que sea considerado no ajustado a la realidad en sus partidas será desestimada.

Conceptos susceptibles de ayuda

a) Gastos de adquisición, alquiler, mantenimiento o reparación de equipamiento científico-técnico de la UNED no inventariable y licencias para programas de ordenador de carácter técnico necesarios para la investigación del proyecto.

b) Gastos de material fungible, suministros y productos similares, excluyendo material de oficina e informático.

c) Gastos de viajes y alojamiento, asistencia a congresos y conferencias, visitas y estancias breves de investigadores, tanto de invitados como del equipo de investigación del proyecto.

d) Gastos derivados de actividades de formación imprescindibles para la ejecución del proyecto. Queda excluida la organización de actividades científico-técnicas y congresos.
-->
```

<!-- IMPS 2024: 725$ (late registration, https://www.psychometricsociety.org/imps2024-registration) Contar con posible subida de precio y fluctuación dólar -->

{{< pagebreak >}}

# Conformidad de participación

<!-- Todas las personas que integren el equipo investigador deberán firmar en la solicitud su conformidad de participación en el proyecto. -->
